---
- name: Install required gems
  gem:
    name: "{{ item }}"
    state: present
    user_install: no
  with_items:
    - sinatra
    - jenkins_api_client
    - net-ldap

- name: Make some directories
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    owner: jenkinspush
    group: jenkinspush
    mode: 0755
  with_items:
    - /home/jenkinspush/jonkins/public
    - /home/jenkinspush/jonkins/views

- name: Move main chunk of ruby into place
  copy:
    src: main.rb
    dest: /home/jenkinspush/jonkins/main.rb
    owner: jenkinspush
    group: jenkinspush
    mode: 0644

- name: Move view files into place
  copy:
    src: "views/{{ item }}"
    dest: /home/jenkinspush/jonkins/views/{{ item }}
    owner: jenkinspush
    group: jenkinspush
    mode: 0644
  with_items:
    - layout.erb
    - list.erb
    - login.erb

- name: template env/config in
  template:
    src: "{{ item }}"
    dest: /home/jenkinspush/jonkins/{{ item }}
    owner: jenkinspush
    group: jenkinspush
    mode: 0644
  notify: restart jonkins
  with_items:
    - config.yml
    - env.rb

- name: Add unit file
  copy:
    src: jonkins.service
    dest: /etc/systemd/system/jonkins.service
    owner: root
    group: root
    mode: 0644

- name: Start/enable it
  systemd:
    name: jonkins
    state: started
    enabled: true
    daemon_reload: yes
